from . import res_partner
from . import project
from . import hr
from . import purchase
from . import repair
from . import task_checklist_repair
from . import hr_timesheet
from . import mail_invite
from . import hr_expense
from . import product
from . import fleet
from . import holiday_wizard
from . import hr_contract
from . import hr_payslip
from . import hr_payslip_worked_days
from . import hr_work_entry
