from . import hr_contract
from . import hr_employee
from . import hr_payroll_structure
from . import res_company
from . import hr_payslip
from . import hr_payslip_run
from . import allowance_line
from . import hr_salary_attachment
from . import hr_leave